### ISSUE TITLE
Additional instructions to run netwarp_test

### ISSUE THREAD

**Issue by akshata-bhat** [lxtGH/netwarp_test#1]
Hello Latou,
(@lxtGH )

I am trying to run the netwarp_test model. Are there any additional steps to be followed to run the extract_opticalflow.py file?

The file names in the val and test directories of cityscapes dataset are not sequential. Hence the script used to calculate the optical flow is giving me errors. How did you manage to run? What changes did you have to make? 

Also what changes did you make in your code - which are different from the netwarp_public model?

Thanks,
Akshata

**Comment by lxtGH** [comment]
@akshata-bhat just calculate the flow between previous image and second image(val image)
I just eval the model and remove multi scale prediction, the model can't be train and the result is not consistent with his paper.

**Comment by akshata-bhat** [comment]
@lxtGH I really need some more help and guidance from you. I have been trying to get the model to run for 1.5 weeks now and have been unsuccessful.
1) Can you please elaborate on what you mean by remove multi scale prediction? 
2) Also could you share a few images of the frames after semantic segmentation?
3) Which of your scripts are different from that of netwarp_public/scripts? I was unable to find the differences.

Thanks,
Akshata

**Comment by lxtGH** [comment]
@akshata-bhat Sorry for late reply.
1, To save the testing time.
2, You can use the pretrained model that he provide to get the output.
3, I only change the code that it can run the prediction. The final result is a little lower than his paper.
